FLATCC_BUILD_CONFIG=make
FLATCC_BUILD_GEN="-G Unix Makefiles"

FLATCC_BUILD_SYSTEM=cmake
FLATCC_BUILD_CMD=make
FLATCC_TEST_CMD=ctest

FLATCC_BUILD_FLAGS=""
FLATCC_TARGET_RELEASE="-DCMAKE_BUILD_TYPE=Release"
FLATCC_TARGET_DEBUG="-DCMAKE_BUILD_TYPE=Debug"
